config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home_page#index'
  get 'home/index', to: 'home_page#index', as: '/'
  get 'home/:id', to: 'home_page#show', as: 'home_show'

  resources :contacts, only: [:new, :create]
  resources :jobs, only: [:new, :create, :show]
  resources :search, only: [:index]

  # get 'freelancer/rails', to: 'freelancer#rails'
  # get 'freelancer/scrape', to: 'freelancer#scrape'
  #
  # get 'upwork/rails', to: 'upwork#rails'
  # get 'upwork/scrape', to: 'upwork#scrape'
  # get 'upwork/ruby', to: 'upwork#ruby'
  #
  # get 'weworkremotely', to: 'weworkremotely#rails'
  # get 'indeed', to: 'indeed#rails'
  # get 'stackjobs', to: 'stackjobs#rails'
  # get 'github/:id', to: 'github#show', as: 'github'
  # get 'github/show', to: 'github#show'
  # resources :githubs, only: [:show]
  # get 'cybercoders', to: 'cybercoders#rails'
  # get 'careerbuilder', to: 'careerbuilder#rails'
  # get 'remotelyawesome', to: 'remotelyawesome#rails'
  #
  # get 'main/payment', to: 'main#payment'


  # resources :contracts do #add preview later
  #   get 'preview'
  # end

  # resource :charges, only: [:new, :create, :invoice] do
  #   get 'invoice'
  # end

  # resource :job_charges, only: [:new, :create, :invoice] do
  #   get 'invoice'
  # end
end

app/models/careerbuilder.rb
class Careerbuilder < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/contract.rb
class Contract < ApplicationRecord
  
  
  
  validates :title, presence: true,
                    length: { minimum: 1, maximum: 70 }
  validates :description,  presence: true,
                    length: { minimum: 1, maximum: 700 }
                    
  validates :email,  presence: true,
                    length: { minimum: 1 }                  
  
  
end

app/models/cybercoder.rb
class Cybercoder < ApplicationRecord
end

app/models/freelancerail.rb
class Freelancerail < ApplicationRecord
end

app/models/github.rb
class Github < ApplicationRecord
end

app/models/indeed_rail.rb
class IndeedRail < ApplicationRecord
end

app/models/job.rb
class Job < ApplicationRecord
  include PgSearch

  validates :title, :email, :description, presence: true

  pg_search_scope :search, against: [:title, :description, :source],
  using: {
    :tsearch => {:prefix => true, dictionary: "english"}
  }

  default_scope {order(date: :desc)}
end

app/models/scrape.rb
class Scrape < ApplicationRecord
  include PgSearch

  pg_search_scope :search, against: [:title, :description, :source],
  using: {
    :tsearch => {:prefix => true, dictionary: "english"}
  }

  default_scope {order(date: :desc)}
end

app/models/stack_job.rb
class StackJob < ApplicationRecord
end

app/models/upwork_rail.rb
class UpworkRail < ApplicationRecord
end

app/models/upwork_ruby.rb
class UpworkRuby < ApplicationRecord
end

app/models/upwork_scrape.rb
class UpworkScrape < ApplicationRecord
end

app/models/wework_rail.rb
class WeworkRail < ApplicationRecord
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  before_action :g_ads

  def index
    if params[:page].to_i > 1
      @jobs = Scrape.paginate(page: params[:page], per_page: 50)
      if Job.count > 0
        @rjh_jobs = Job.all.paginate(page: params[:page], per_page: 50)
        @job = Job.first
      else
        @job = Scrape.first
      end
      render partial: 'job_meta'
    elsif params[:id]
      @job = Scrape.find_by(job_id: params[:id])
      @jobs = Scrape.where.not(job_id: params[:id]).first(50)
      if Job.count > 0
        @rjh_jobs = Job.first(50)
        if @job
          @rjh_jobs.to_a.prepend(@job)
        else
          @job = @rjh_jobs.first
        end
      else
        if @job
          @jobs.to_a.prepend(@job)
        else
          @job = @jobs.first
        end
      end
    else
      @jobs = Scrape.paginate(page: params[:page], per_page: 50)
      if Job.count > 0
        @rjh_jobs = Job.all.paginate(page: params[:page], per_page: 50)
        @job = Job.first
      else
        @job = Scrape.first
      end
    end
  end

  def show
    puts params
    @job = Scrape.find_by_id(params[:id])
    render partial: 'job_description'
  end

  private

  def g_ads
    @g_ads = true
  end

end

app/controllers/sessions.rb
class SessionsController < ApplicationController
  
  def new
    @meta_tag = "noindex nofollow"
  end
  
  def create
    session[:current_user_id] = @user.id

  # @user = User.find_by_username(params[:session][:username])
  # if @user && @user.authenticate(params[:session][:password])
  #   session[:user_id] = @user.id
  #   redirect_to '/forums'
  # else
  #   redirect_to new_session_path
  #   flash[:alert] = "Oops.. Houston, we have a problem..."
  # end 
  end
  
  def destroy
    @meta_tag= "noindex"
    
    session[:user_id] = nil
    redirect_to root_path
  end
  
  
  
end

app/helpers/home_page_helper.rb
module HomePageHelper

  def humanDate(date)
    ts = Time.now - date
    ts_days = ts / 86400
    if ts_days <= 1
      return 'Today'
    else
      return ts_days.to_i.to_s + "d"
    end
  end

end

app/helpers/indeed_helper.rb
module IndeedHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/upwork_helper.rb
module UpworkHelper
end

app/views/home_page/_job_description.html.erb
<div data-change="change->scrollbar#fixScrollbar" class="google_adsense" style="overflow-x:hidden;">
  <ins class="adsbygoogle"
       style="display:block; text-align:center;"
       data-ad-layout="in-article"
       data-ad-format="fluid"
       data-ad-client="ca-pub-5374261406606651"
       data-ad-slot="4175240466"></ins>
  <script>
   (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
</div>

<div class="title_description">
  <h3>
    <%= @job.title %>
  </h3>
  <div class="meta_description">
    <div>
      <span><%= humanDate(@job.date) %> - </span>
      <span><%= @job.source %></span>
    </div>
    <div>
      <span><%= @job.company %> - </span>
      <span><%= @job.location %></span>
    </div>
  </div>
</div>

<div class="job__description">
  <%= @job.description.html_safe %>
</div>
<div class="text-center">
  <a href=<%=@job.link%> target="_blank">
    <button class="btn btn-lg btn-success">
      Apply Here!
    </button>
  </a>
</div>

app/views/home_page/_job_meta.html.erb
<% if @rjh_jobs %>
  <%= render 'home_page/rjh_meta' %>
<% end %>
<% @jobs.each do |job| %>
    <div data-controller="job" data-job-id="<%= job.id %>">
      <%= link_to( home_show_path(job), type: "html",
                   data: { action: "ajax:success->job#jobAjax
                                    ajax:error->job#jobAjaxFail
                                    ajax:before->job#jobClick"},
                   remote: true ) do %>
        <span class="job">
          <span class="job__title">
            <h5><%= job.title %></h5>
          </span>
          <span class="job__meta">
            <span class="job__date">
              <%= humanDate(job.date) %>
            </span>
            <span class="job__company">
              <%= job.company if job.company %>
            </span>
            <span class="job__location">
              <%= job.location if job.location %>
            </span>
            <span class="job__source">
              <%= job.source %>
            </span>
          </span>
        </span>
      <% end %>
    </div>
<% end %>

app/views/home_page/_rjh_meta.html.erb
<% @rjh_jobs.each do |job| %>
  <div data-controller="job">
    <%= link_to( job_path(job), type: "html",
                 data: { action: "ajax:success->job#jobAjax
                                  ajax:error->job#jobAjaxFail
                                  ajax:before->job#jobClick"},
                 remote: true ) do %>
      <span class="job">
        <span class="job__title">
          <h5><%= job.title %></h5>
        </span>
        <span class="job__meta">
          <span class="job__date">
            <%= humanDate(job.date) %>
          </span>
          <span class="job__company">
            <%= job.company if job.company %>
          </span>
          <span class="job__location">
            <%= job.location if job.location %>
          </span>
          <span class="job__source">
            <%= job.source %>
          </span>
        </span>
      </span>
    <% end %>
  </div>
<% end %>

app/views/home_page/index.html.erb
<div data-controller="scrollbar" class="grid" id="scrollbar">
  <%= render 'layouts/header' %>

  <div data-target="scrollbar.left"
       data-action="ps-y-reach-end->scrollbar#scrollBottom"
       class="grid__left">
    <%= render 'home_page/job_meta' %>
    <div data-controller="job-meta" class="text-center">
      <%= button_to( root_path, type: "html",
                   class: "btn btn-lg btn-primary load_jobs",
                   method: :get, params: {page: "2"}, remote: true) do %>
        <span class="load__button">
          Load More Jobs
        </span>
      <% end %>
    </div>
  </div>

  <div data-target="scrollbar.right" data-action="change->scrollbar#scrollTop" class="grid__right" id="job_description">
    <%= render 'home_page/job_description' %>
  </div>

  <%= render 'layouts/footer' %>

</div>

app/views/home_page/test.html.erb
<% @jobs.each do |job| %>
    <div data-controller="job" data-job-id="<%= job.id %>">
      <%= link_to( home_show_path(job), type: "html",
                   data: { action: "ajax:success->job#jobClick
                                    ajax:error->job#jobClickFail" },
                   remote: true ) do %>
        <div class="job">
          <div class="job__title">
            <h4><%= job.title %></h4>
          </div>
          <div class="job__meta">
            <div class="job__date">
              <%= job.date %>
            </div>
            <div class="job__company">
              <%= job.company %>
            </div>
            <div class="job__location">
              <%= job.location %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
<% end %>