config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home_page#index'
  get 'home/index', to: 'home_page#index', as: '/'
  get 'home/:id', to: 'home_page#show', as: 'home_show'

  resources :contacts, only: [:new, :create]
  resources :jobs, only: [:new, :create, :show]
  resources :search, only: [:index]

  # get 'freelancer/rails', to: 'freelancer#rails'
  # get 'freelancer/scrape', to: 'freelancer#scrape'
  #
  # get 'upwork/rails', to: 'upwork#rails'
  # get 'upwork/scrape', to: 'upwork#scrape'
  # get 'upwork/ruby', to: 'upwork#ruby'
  #
  # get 'weworkremotely', to: 'weworkremotely#rails'
  # get 'indeed', to: 'indeed#rails'
  # get 'stackjobs', to: 'stackjobs#rails'
  # get 'github/:id', to: 'github#show', as: 'github'
  # get 'github/show', to: 'github#show'
  # resources :githubs, only: [:show]
  # get 'cybercoders', to: 'cybercoders#rails'
  # get 'careerbuilder', to: 'careerbuilder#rails'
  # get 'remotelyawesome', to: 'remotelyawesome#rails'
  #
  # get 'main/payment', to: 'main#payment'


  # resources :contracts do #add preview later
  #   get 'preview'
  # end

  # resource :charges, only: [:new, :create, :invoice] do
  #   get 'invoice'
  # end

  # resource :job_charges, only: [:new, :create, :invoice] do
  #   get 'invoice'
  # end
end

app/models/careerbuilder.rb
class Careerbuilder < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/contract.rb
class Contract < ApplicationRecord
  
  
  
  validates :title, presence: true,
                    length: { minimum: 1, maximum: 70 }
  validates :description,  presence: true,
                    length: { minimum: 1, maximum: 700 }
                    
  validates :email,  presence: true,
                    length: { minimum: 1 }                  
  
  
end

app/models/cybercoder.rb
class Cybercoder < ApplicationRecord
end

app/models/freelancerail.rb
class Freelancerail < ApplicationRecord
end

app/models/github.rb
class Github < ApplicationRecord
end

app/models/indeed_rail.rb
class IndeedRail < ApplicationRecord
end

app/models/job.rb
class Job < ApplicationRecord
  include PgSearch

  validates :title, :email, :description, presence: true

  pg_search_scope :search, against: [:title, :description, :source],
  using: {
    :tsearch => {:prefix => true, dictionary: "english"}
  }

  default_scope {order(date: :desc)}
end

app/models/scrape.rb
class Scrape < ApplicationRecord
  include PgSearch

  pg_search_scope :search, against: [:title, :description, :source],
  using: {
    :tsearch => {:prefix => true, dictionary: "english"}
  }

  default_scope {order(date: :desc)}
end

app/models/stack_job.rb
class StackJob < ApplicationRecord
end

app/models/upwork_rail.rb
class UpworkRail < ApplicationRecord
end

app/models/upwork_ruby.rb
class UpworkRuby < ApplicationRecord
end

app/models/upwork_scrape.rb
class UpworkScrape < ApplicationRecord
end

app/models/wework_rail.rb
class WeworkRail < ApplicationRecord
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :trix, only: [:new, :show, :create]
  before_action :nofollow, only: [:new, :create, :edit, :update, :show]
  before_action :g_ads

  def new
    @job = Job.new
  end

  def show
    @job = Job.find(params[:id])
    render partial: 'home_page/job_description'
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      skills = []
      skills_pre = job_params[:skills].split(',')
      skills_pre.each { |x| skills << x.strip }
      @job.update(skills: skills, source: "RailsJobHub",
        date: Time.now.utc, job_id: @job.id)
      session[:job_id] = @job.id
      redirect_to root_path
    else
      render :new
    end
  end


  private

  def job_params
    params.require(:job).permit(:title, :description, :email, :link,
                                :location, :price, :company, :skills)
  end

  def trix
    @trix = true
  end

  def nofollow
    @nofollow = 1
  end

  def g_ads
    @g_ads = false
  end
end

app/controllers/sessions.rb
class SessionsController < ApplicationController
  
  def new
    @meta_tag = "noindex nofollow"
  end
  
  def create
    session[:current_user_id] = @user.id

  # @user = User.find_by_username(params[:session][:username])
  # if @user && @user.authenticate(params[:session][:password])
  #   session[:user_id] = @user.id
  #   redirect_to '/forums'
  # else
  #   redirect_to new_session_path
  #   flash[:alert] = "Oops.. Houston, we have a problem..."
  # end 
  end
  
  def destroy
    @meta_tag= "noindex"
    
    session[:user_id] = nil
    redirect_to root_path
  end
  
  
  
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/githubs_helper.rb
module GithubsHelper
end

app/helpers/indeed_helper.rb
module IndeedHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/upwork_helper.rb
module UpworkHelper
end

app/views/jobs/_empty.html.erb
<div class="col-xs-6 left-col">
  <div class="text-center col-xs-12 box empty-contracts">
     <h1> Welcome to Rails Job Hub</h1>
     <h2> Contract Job Postings</h2>
     <h3>*If You Are Looking for a Top Rails or Ruby Developer You Have <br> Come to the Right Site</h3>
     <h3>Rails Job Hub is the premier jobsite for Rails and Ruby developers. Rails Job Hub aggregates 
     all the major job websites for Rails, Ruby, and web scrapping jobs. </h3>
      <ul>
       <li>
         Your contract job listing will remain on this site for 30 days.
       </l1>
       <li>
         After seven days your listing will be removed.
       </li>
       <li>
       You can always post your job listing for $199.00 for another 30 days.
       </li> 
      </ul>

  </div>
</div>
<div class="col-xs-6 right-col">
  <div class="col-xs-12 box">
    
      <div class="col-xs-12 job-title"><h1 class="contracts-title">Your Job Title Here </h1></div>
      <div class="col-xs-12 job-description">
          In this section you describe what the job is and how people are to get contant you.</div>
      <div class="col-xs-4">Date of Posting</div>
    </div>
    
  </div>
</div>

app/views/jobs/_job.html.erb
<div>
  <a href="#" onClick="event.preventDefault()">
    <span class="job">
      <span class="job__title">
        <h4 data-target="job-post--job-meta.title">Your Title Here</h4>
      </span>
      <span class="job__meta">
        <span class="job__date">
          Today
        </span>
        <span class="job__company" data-target="job-post--job-meta.company">
          Company
        </span>
        <span class="job__location" data-target="job-post--job-meta.location">
          Location
        </span>
      </span>
    </span>
  </a>
</div>

app/views/jobs/_job_description.html.erb
<div data-target="scrollbar.right" class="grid__right_job">
  <div class="title_description">
    <h3 id="title_description">
      Your Title Here
    </h3>
    <div class="meta_description">
      <div>
        <span>Today - </span>
        <span>RailsJobHub</span>
      </div>
      <div>
        <span id="company_description">Company - </span>
        <span id="location_description">Location</span>
      </div>
    </div>
  </div>

  <div class="job__description" id="job_description"
    data-action="change->scrollbar#scrollTop">
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Netus et malesuada fames ac. Lectus quam id leo in vitae turpis massa. Vel elit scelerisque mauris pellentesque pulvinar. Id diam vel quam elementum pulvinar etiam non quam. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Donec massa sapien faucibus et molestie ac. Euismod lacinia at quis risus. Luctus accumsan tortor posuere ac ut. Vel orci porta non pulvinar neque laoreet suspendisse interdum. Nunc pulvinar sapien et ligula ullamcorper malesuada. Ultricies integer quis auctor elit. Lorem dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Egestas quis ipsum suspendisse ultrices gravida dictum fusce ut placerat. Nisi vitae suscipit tellus mauris. Cursus in hac habitasse platea dictumst quisque sagittis purus sit. Ante in nibh mauris cursus mattis molestie a iaculis. Posuere urna nec tincidunt praesent semper. Augue neque gravida in fermentum et.
    </p>
    <p>
      Nunc vel risus commodo viverra. Urna duis convallis convallis tellus. Quis commodo odio aenean sed adipiscing. Luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor purus. Pretium viverra suspendisse potenti nullam. Varius duis at consectetur lorem donec massa sapien faucibus et. Sed vulputate odio ut enim. Malesuada proin libero nunc consequat interdum varius sit amet. Ut faucibus pulvinar elementum integer. Luctus accumsan tortor posuere ac ut consequat semper viverra. Faucibus scelerisque eleifend donec pretium vulputate. Volutpat est velit egestas dui id ornare. Id aliquet risus feugiat in ante metus dictum at tempor. Urna nec tincidunt praesent semper feugiat nibh sed pulvinar proin. Nullam eget felis eget nunc lobortis mattis aliquam faucibus purus. Semper viverra nam libero justo laoreet sit amet. Ut consequat semper viverra nam libero. Adipiscing commodo elit at imperdiet dui accumsan.
    </p>
    <p>
      Vitae tempus quam pellentesque nec. Magna ac placerat vestibulum lectus mauris ultrices. Ridiculus mus mauris vitae ultricies leo integer. Ut diam quam nulla porttitor massa id neque aliquam vestibulum. Et magnis dis parturient montes nascetur ridiculus mus. Enim nec dui nunc mattis. Enim facilisis gravida neque convallis a cras. Faucibus pulvinar elementum integer enim neque volutpat ac. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus. Pellentesque habitant morbi tristique senectus. Commodo nulla facilisi nullam vehicula ipsum a arcu cursus. Et malesuada fames ac turpis egestas integer eget aliquet. Arcu odio ut sem nulla pharetra. Sem fringilla ut morbi tincidunt augue interdum velit euismod in. Tellus id interdum velit laoreet id donec ultrices tincidunt arcu. Purus faucibus ornare suspendisse sed nisi. Integer feugiat scelerisque varius morbi enim nunc faucibus. Viverra maecenas accumsan lacus vel facilisis volutpat est velit egestas. A pellentesque sit amet porttitor eget dolor morbi non arcu. Facilisi etiam dignissim diam quis enim.
    </p>
  </div>
  <div class="text-center">
    <a href="#" onClick="event.preventDefault()">
      <button class="btn btn-lg btn-success">
        Apply Here!
      </button>
    </a>
  </div>
</div>

app/views/jobs/_job_post.html.erb
<div>
  <a href="#" onClick="event.preventDefault()">
    <span class="job">
      <span class="job__title">
        <h5 data-target="job-post--job-meta.title">Your Title Here</h5>
      </span>
      <span class="job__meta">
        <span class="job__date">
          Today
        </span>
        <span class="job__company" data-target="job-post--job-meta.company">
          Company
        </span>
        <span class="job__location" data-target="job-post--job-meta.location">
          Location
        </span>
        <span>
          RailsJobHub
        </span>
      </span>
    </span>
  </a>
</div>

app/views/jobs/edit.html.erb
<% provide(:title, @job.title) %>
<div class="col-xs-7 col-xs-offset-2 create-contract ">
  <div class="col-xs-6 row ">
   <%= image_tag("RailsJobHub.jpg", class: "img-responsive") %>
  </div>

<div class="form-group col-xs-12 ">
  
  <%= form_for @job do |f| %>
    <% if @job.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@job.errors.count, "error") %> prohibited
              this article from being saved:
        </h2>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </div>
    <% end %>

 <%= f.label :title %><br>
  <%= f.text_field :title, class: "form-control input-lg" %>
  <br>
  <%= f.label :description %><br>
  <%= f.text_area :description, class: "form-control input-lg wysihtml5", rows: 8 %>
  
   <script type="text/javascript">
  $(document).ready(function(){

    $('.wysihtml5').each(function(i, elem) {
      $(elem).wysihtml5();
    });

  })
</script>
  
 
  
  <br>
  <%= f.label :email %>
  <%= f.text_field :email, class: "form-control input-lg" %>
  <br>
   <%= f.label :Upload_Your_Logo %>
  <%= f.file_field :logo, class: "" %>
  <br>
  <%= f.label :How_do_applicants_apply? %>
  <%= f.text_field :applyinfo, class: "form-control input-lg" %>
  <br>
  
  
  
  
  
  
  <%= f.submit "Update Posting", class: "btn btn-primary btn-lg" %>
  
<% end %>

app/views/jobs/index.html.erb
<div class="col-xs-12" id="body-contracts">
  <% if @valid_job_array.empty? %>
    <%= render 'jobs/empty' %>
  <% else %>
    <%= render 'jobs/job' %>
  <% end %>
</div>

app/views/jobs/new.html.erb
<div data-controller="scrollbar" class="grid">
  <%= render 'layouts/header' %>

  <div data-controller="job-post--job-meta" data-target="scrollbar.left"
       class="grid__left">
    <%= render 'jobs/job_post' %>
    <div class="job_post form-group col-xs-12">
      <%= form_for @job do |f| %>
        <% if @job.errors.any? %>
          <ul class="job_post__error_count">
            <li class="job_post__error"><%= @job.errors.count %> errors prevented your post!</li>
          </ul>
        <% end %>
        <div class="job_post__title">
          <%= f.label :title, "Title:" %>
          <%= f.text_field :title, class: "form-control form-control-sm",
            data: {action: 'input->job-post--job-meta#changeTitle',
            target: 'job-post--job-meta.titleFocus'} %>
          <% if @job.errors[:title].any? %>
          <div class="job_post__error">
            Title: <%= @job.errors[:title].first %>
          </div>
          <% end %>
        </div>
        <div class="job_post__company">
          <%= f.label :company, "Company:" %>
          <%= f.text_field :company, class: "form-control form-control-sm",
          data: {action: 'input->job-post--job-meta#changeCompany'}%>
        </div>
        <div class="job_post__location">
          <%= f.label :location, "Location:" %>
          <%= f.text_field :location, class: "form-control form-control-sm",
          data: {action: "input->job-post--job-meta#changeLocation"}%>
        </div>
        <div class="job_post__skills">
          <%= f.label :skills, "Skills. Seperate by commas :" %>
          <%= f.text_field :skills, class: "form-control form-control-sm" %>
        </div>
        <div class="job_post__link">
          <%= f.label :link, "Link for candidates to apply to:" %>
          <%= f.text_field :link, class: "form-control form-control-sm" %>
          <% if @job.errors[:link].any? %>
          <div class="job_post__error">
            Link: <%= @job.errors[:link].first %>
          </div>
          <% end %>
        </div>
        <div class="job_post__email">
          <%= f.label :email, "Email for if we need to contact you:" %>
          <%= f.text_field :email, class: "form-control form-control-sm" %>
          <% if @job.errors[:email].any? %>
          <div class="job_post__error">
            Email: <%= @job.errors[:email].first %>
          </div>
          <% end %>
        </div>
        <div class="job_post__price">
          <%= f.label :price, "How much would you pay for a month?"%>
          <%= f.number_field :price, class: "form-control form-control-sm"%>
        </div>
        <div class="job_post__description">
          <%= f.label :description, "Description:" %>
          <% if @job.errors[:description].any? %>
          <div class="job_post__error">
            Description: <%= @job.errors[:description].first %>
          </div>
          <% end %>
          <%= f.hidden_field :description, value: @job.description, id: "trix" %>
          <trix-editor input="trix" data-controller="job-post--job-description"
            data-action="trix-change->job-post--job-description#changeDescription"
            class="trix_editor">
          </trix-editor>
        </div>
        <div class="job_post__submit text-center">
          <%= f.submit "Create Job Post", class: "btn btn-primary btn-lg",
          data: {confirm: "Everything Look Good?"}%>
        </div>
      <% end %>
    </div>
  </div>

  <%= render 'jobs/job_description' %>

</div>

app/views/jobs/show.html.erb
<% provide(:title, @job.title) %>
<div class="col-xs-7 col-xs-offset-2 create-contract ">
  
  <div class="col-xs-12">
    <div class="col-xs-6 row ">
      <%= image_tag("RailsJobHub.jpg", class: "img-responsive") %>
     </div>
  </div> 
  
  <h1 class="col-xs-12 "><%= image_tag(@job.logo, class: "img-responsive") %><%= @job.title %></h1>
  
  <p class="col-xs-12"><%= @job.description.html_safe %></p>
  
  <p class="col-xs-12"><%= @job.applyinfo %></p>
  
  <div class="col-xs-12 buttons ">
    <%= link_to edit_job_path(@job.id) do %>
      <button class="btn btn-lg btn-primary">Edit</button>
    <% end %>
    <%= link_to :controller => "job_charges", action: "new" do %>
      <button class="btn btn-lg btn-danger buttons-checkout">Looks Great! Go to Checkout</button>
    <% end %>
  </div>
</div>

app/views/jobs/test.html.erb
<div class="col-xs-7 col-xs-offset-2 create-contract">
  <div class="col-xs-6 image-header-shit">
   <%= image_tag("RailsJobHub.jpg", class: "img-responsive") %>
  </div>
  <div class="col-xs-6 contract-job-explanation">
    Your permanent job listing will remain on this site for 30 days.  After thirty days your listing will be 
    removed.  You can always post your permanent job listing again for $199.00 for another 30 days.  
  </div>
    <h1 class="col-xs-12"> CREATE YOUR AD</h1>
<div class="form-group col-xs-12">
  <%= form_for @job do |f| %>
  
  <%= f.label :title %><br>
  <%= f.text_field :title, class: "form-control input-lg" %>
  <br>
  <%= f.label :description %><br>
  <%= f.text_area :description, class: "form-control input-lg wysihtml5", id: "contract-content" %>
  <div id="count"></div>
  <br>
  <%= f.label :email %>
  <%= f.text_field :email, class: "form-control input-lg" %>
  <br>
  <%= f.label :Upload_Your_Logo %>
  <%= f.file_field :logo, class: "" %>
  <br>
  <%= f.label :How_do_applicants_apply? %>
  <%= f.text_field :applyinfo, class: "form-control input-lg" %>
  
  
  <script type="text/javascript">
  $(document).ready(function(){

    $('.wysihtml5').each(function(i, elem) {
      $(elem).wysihtml5({'toolbar':{ 'blockquote': true, 'html': false, 'image': false, 'lists': false, 'link': false},
        'events': {
            'load': function() {
              var editor = this;
              $(editor.currentView.doc.body).on("keyup",function(event) {
                var l = event.currentTarget.innerText.length;
                if(l >= 12000) {
                  $('#count').html('<span class="text-danger">Total characters exceed 12000. Extra characters will not be saved.</span>');
                } else {
                  var left = 12000 - l;
                  $('#count').html('<span class="text-info">'+ left + ' characters left ' +'</span>');
                }
              }); 
            }
          }
      });
      
    });

  })
  
 
</script>
  <br>
   <%#  f.submit 'Preview', name: 'preview_button'  %>
   <%= f.submit "Create Job Post", class: "btn btn-primary btn-lg" %>
  <% end %>
</div>
</div>